apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  labels:
    app: store
    group: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
      group: frontend
  template:
    metadata:
      labels:
        app: store
        group: frontend
    spec:
      containers:
        - name: main
          image: store.frontend.local:0.0.1
          ports:
            - containerPort: 80
          # resources:
          #   limits:
          #     cpu: 500m
          #     memory: 1Gi
          #   requests:
          #     cpu: 100m
          #     memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: store
  labels:
    app: store
    group: frontend
spec:
  type: NodePort
  selector:
    app: store
    group: frontend
  ports:
    - port: 80
      targetPort: 80