apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    group: {{ .Values.group }}
    version: {{ .Values.version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      group: {{ .Values.group }}
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        group: {{ .Values.group }}
        version: {{ .Values.version }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          image: {{ printf "\"%s:%s\"" .Values.image .Values.version }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          env:
            - name: EVENTS_EXTERNAL_URI
              value: {{ printf "\"%s://%s:%s%s\"" .Values.events.external.protocol ( default .Values.backend.ip .Values.backend.hostname ) ( toString .Values.events.external.port ) .Values.events.external.path }}
            - name: EVENTS_INTERNAL_URI
              value: {{ printf "\"%s://%s:%s%s\"" .Values.events.internal.protocol .Values.events.internal.hostname ( toString .Values.events.internal.port ) .Values.events.internal.path }}
            - name: RESOURCES_EXTERNAL_URI
              value: {{ printf "\"%s://%s:%s%s\"" .Values.resources.external.protocol ( default .Values.backend.ip .Values.backend.hostname ) ( toString .Values.resources.external.port ) .Values.resources.external.path }}
            - name: RESOURCES_INTERNAL_URI
              value: {{ printf "\"%s://%s:%s%s\"" .Values.resources.internal.protocol .Values.resources.internal.hostname ( toString .Values.resources.internal.port ) .Values.resources.internal.path }}
            - name: PRODUCTS_EXTERNAL_URI
              value: {{ printf "\"%s://%s:%s%s\"" .Values.products.external.protocol ( default .Values.backend.ip .Values.backend.hostname ) ( toString .Values.products.external.port ) .Values.products.external.path }}
            - name: PRODUCTS_INTERNAL_URI
              value: {{ printf "\"%s://%s:%s%s\"" .Values.products.internal.protocol .Values.products.internal.hostname ( toString .Values.products.internal.port ) .Values.products.internal.path }}
            - name: CONTACT_EMAIL
              value: {{ .Values.email | quote }}
            - name: PORT
              value: "80"
            - name: HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    group: {{ .Values.group }}
    version: {{ .Values.version }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.name }}
    group: {{ .Values.group }}
    version: {{ .Values.version }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 80
