apiVersion: batch/v1
kind: Job
metadata:
  name: init-cms
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        component: init
        app: cms
        group: frontend
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: init-cms.frontend.local:{{ .Values.cms.version }}
      