apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  labels:
    app: store
    group: frontend
    version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
      group: frontend
  template:
    metadata:
      labels:
        app: store
        group: frontend
    spec:
      containers:
        - name: main
          image: {{ printf "%s:%s" .Values.image .Chart.AppVersion | quote }}
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          env:
            - name: CMS_URL
              value: {{ .Values.cms.url | quote }}
            - name: PORT
              value: {{ .Values.port | required | quote }}
          ports:
            - containerPort: {{ .Values.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: store
  labels:
    app: store
    group: frontend
spec:
  type: {{ template "helpers.service.type" .Values.env }}
  selector:
    app: store
    group: frontend
  ports:
    - name: http-store
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}