piVersion: v1
name: frontend
version: 0.0.1
description: Frontend to Uni Cycle
keywords:
  - cms
  - nuxt
  - ecommerce
  - recycling
  - student
maintainers:
  - name: Jonathan Cowling
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
# home: The URL of this project's home page (optional)
sources:
  - https://github.com/cowlingj/nuxt-ecommerce
appVersion: 0.0.1
