apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cms
spec:
  hosts:
  - "*"
  gateways:
  - ingress
  http:
  - match:
    - uri:
        prefix: "/cms"
    route:
    - destination:
        port:
          number: {{ .Values.cms.port }}
        host: {{ .Values.cms.host | quote }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cms-graphql
spec:
  hosts:
  - "*"
  gateways:
  - ingress
  http:
  - match:
    - uri:
        prefix: "/cms/graphql"
    route:
    - destination:
        port:
          number: {{ .Values.cms.graphql.port }}
        host: {{ .Values.cms.graphql.host | quote }}