# namespace: default {{ .Release.Namespace }}
env: production
name: store
group: frontend
version: "0.0.2"
image: cowlingj/uni-cycle
imagePullSecrets: []
eamil: null

service:
  type: ClusterIP
  port: 80

backend:
  ip: ""
  hostname: ""

events:
  internal:
    hostname: events
    ip: null
    path: /
    protocol: http
    port: 80
  external:
    path: /events
    protocol: http
    port: 80

resources:
  internal:
    hostname: cms
    ip: null
    path: /
    protocol: http
    port: 80
  external:
    path: /cms/graphql
    protocol: http
    port: 80

products:
  internal:
    hostname: products
    ip: null
    path: /
    port: 80
    protocol: http
  external:
    path: /products
    port: 80
    protocol: http
