# namespace: default {{ .Release.Namespace }}
env: production
name: store
group: frontend
version: "0.0.1"
image: gcr.io/gke-test-253221/store.frontend
imagePullSecret: gcr
ports:
  main:
    name: main
    port: 80
    protocol: http

backend:
  ip: null
  hostname: null

cms:
  api:
    hostname: cms
    basePath: /
    port: 80
    protocol: http
products:
  api:
    hostname: products
    basePath: /
    port: 80
    protocol: http
