# namespace: default {{ .Release.Namespace }}
env: production
name: store
group: frontend
version: "0.0.1"
image: gcr.io/gke-test-253221/store.frontend
imagePullSecret: gcr
ports:
  main:
    name: main
    port: 80
    protocol: http

cms:
  env: production
  name: cms
  group: frontend
  image: "gcr.io/gke-test-253221/cms.admin"
  imagePullSecret: gcr
  version: "0.0.1"
  db: cms
  cookieSecret: tmp
  ports:
    api:
      port: 8080
      protocol: http
      name: api
