# namespace: default {{ .Release.Namespace }}
env: production
name: store
group: frontend
version: "0.0.1"
image: gcr.io/gke-test-253221/store.frontend
imagePullSecret: gcr
ports:
  main:
    name: main
    port: 80
    protocol: http

cms:
  api:
    hostname: cms
    domain: null
    basePath: /
    port: 80
    protocol: http
