name: Terraform Deploy
on:
  push:
    tags:        
      - v.*

env:
  AWS_ACCESS_KEY_ID: AKIA4GTFVI55WFJVRON4
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}" 
  AWS_DEFAULT_REGION: eu-west-2
  AWS_STATE_BUCKET: wildfire-bucket
  AWS_STATE_KEY: wildfire-bucket/dev/terraform

defaults:
  run:
    working-directory: deploy/prod/

jobs:
  deploy:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create backend config secret files
        run: |-
          mkdir -p secrets/backend/
          while read key; do
            jq ".\"$key\"" <<< '${{ secrets.BACKEND_CONFIG }}' > "secrets/backend/$key"
          done < <( jq -r 'keys | .[]' <<< '${{ secrets.BACKEND_CONFIG }}' )
      - name: terraform init
        run: |-
          terraform init \
            --backend-config "region=${{ env.AWS_DEFAULT_REGION }}" \
            --backend-config "key=${{ env.AWS_STATE_KEY }}" \
            --backend-config "bucket=${{ env.AWS_STATE_BUCKET }}"
      - run: terraform apply --auto-approve
