apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
      group: frontend
  template:
    metadata:
      labels:
        app: cms
        group: frontend
    spec:
      initContainers:
        - name: mongodb-probe
          image: busybox:1.30.1
          command: ['sh', '-c', 'for i in {1..6}; do nc -w 5 mongodb:27017 && exit 0; done; exit 1']
      containers:
        - name: main
          image: cms.frontend.local:test
          readinessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
          env:
            - name: DB_NAME
              value: cms
            - name: DB_USER
              value: cms
            - name: DB_PASSWORD
              value: cms
---
apiVersion: v1
kind: Service
metadata:
  name: cms
  labels:
    app: cms
    group: frontend
spec:
  type: NodePort
  selector:
    app: cms
    group: frontend
  ports:
    - port: 80
      targetPort: 80